# Generated by Django 4.1 on 2022-09-01 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_name", models.CharField(max_length=100)),
                ("event_place", models.CharField(max_length=100)),
                ("event_address", models.CharField(max_length=200)),
                ("date_start", models.DateTimeField(verbose_name="Start date")),
                ("date_end", models.DateTimeField(verbose_name="End date")),
                (
                    "event_virtual",
                    models.BooleanField(default=False, verbose_name="Virtual event?"),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(default="admin", max_length=100)),
                (
                    "event_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="events.category",
                    ),
                ),
            ],
        ),
    ]
